spring:
  application:
    name: microsaap

  web:
    resources:
      cache:
        period: 0
        cachecontrol:
          no-store: true
          must-revalidate: true

  datasource:
    url: jdbc:mysql://localhost:3306/microsaap_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false   # Gestionado explícitamente por FlywayConfig.kt

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080

app:
  jwt:
    secret: mySecretKey1234567890abcdefghijklmnopqrstuvwxyz
    expiration: 86400000 # 24 horas en milisegundos

logging:
  level:
    com.owlcode.microsaap: DEBUG
    org.springframework.security: WARN
    org.flywaydb: DEBUG

