CREATE TABLE clases (
    id                          BIGINT AUTO_INCREMENT PRIMARY KEY,
    course_id                   BIGINT       NOT NULL,
    titulo                      VARCHAR(255) NOT NULL DEFAULT '',
    modalidad                   VARCHAR(20)  NOT NULL DEFAULT 'PRESENTIAL',
    docente                     VARCHAR(255),
    aula                        VARCHAR(255),
    enlace                      VARCHAR(500),
    notas                       TEXT,
    start_date                  DATE         NOT NULL,
    end_date                    DATE,
    start_time                  VARCHAR(5),
    end_time                    VARCHAR(5),
    recurrence_type             VARCHAR(20)  NOT NULL DEFAULT 'NONE',
    recurrence_interval         INT          NOT NULL DEFAULT 1,
    recurrence_days_of_week     VARCHAR(20),
    recurrence_end_type         VARCHAR(30)  NOT NULL DEFAULT 'NEVER',
    recurrence_until_date       DATE,
    recurrence_occurrence_count INT,
    days_of_week                VARCHAR(20),
    is_cancelled                BOOLEAN      NOT NULL DEFAULT FALSE,
    parent_series_id            BIGINT,
    created_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_clases_course  FOREIGN KEY (course_id)        REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_clases_parent  FOREIGN KEY (parent_series_id) REFERENCES clases  (id) ON DELETE SET NULL,
    INDEX idx_clases_course_id  (course_id),
    INDEX idx_clases_start_date (start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
